# Generated by Django 5.1.2 on 2024-10-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_completed_at_alter_task_priority_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user",
            new_name="owner",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed_at",
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
